# Use a Python runtime with mpi4py pre-installed
FROM python:3.9-slim

# Install MPICH for MPI support and Python packages
RUN apt-get update && apt-get install -y mpich \
    && pip install mpi4py pandas

# Set the working directory in the container
WORKDIR /app

# Copy the worker Python script to the container
COPY q1/q1_mpi.py /app/

# Install additional Python packages if necessary
RUN pip install pandas

# Command to run the worker node script with MPI
CMD ["mpirun", "-np", "1", "python", "/app/q1_mpi.py"]

#to keep the node running to view the IP PORT
#CMD ["sh", "-c", "python /app/q1_mpi.py && tail -f /dev/null"]
